spinestack:
  workspace: localdb
  database:
    file: \${spinestack.config-dir}/\${spinestack.workspace}.sqlite
  lucene:
    data-directory: \${spinestack.config-dir}/lucene/\${spinestack.workspace}

spring:
  artemis:
    embedded:
      data-directory: \${spinestack.config-dir}/artemis/\${spinestack.workspace}
